controller_names:
  - xarm5_traj_controller
  - xarm_gripper

xarm5_traj_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5

xarm_gripper:
  action_ns: gripper_action
  type: GripperCommand
  default: true
  joints:
    - drive_joint
